// Vertical registry — add new verticals here, they appear everywhere in the UI

export const VERTICALS = {
  roofing: {
    id: "roofing",
    label: "Roofing",
    icon: "🏠",
    status: "live",
    workerEndpoint: "/analyze-roof",
    description: "Full roof replacement — pitch detection, squares, Good/Better/Best pricing",
    avgTicket: "$12,500",
    pricebookQuestions: [
      {
        id: "region",
        type: "choice",
        question: "What region are you working in?",
        hint: "This pre-fills labor and material rates for your market.",
        options: [
          { value: "southeast",   label: "Southeast / Florida",     desc: "Lower labor, minimal ice & water" },
          { value: "midatlantic", label: "Mid-Atlantic / Maryland", desc: "Moderate climate, freeze-thaw zones" },
          { value: "northeast",   label: "Northeast / New York",    desc: "Higher labor, full ice & water" },
          { value: "midwest",     label: "Midwest",                 desc: "Moderate rates, seasonal demand" },
          { value: "custom",      label: "Custom — enter manually", desc: "" },
        ],
      },
      {
        id: "labor",
        type: "currency",
        question: "Base install labor rate per square?",
        hint: "Your rate at a standard 6/12 pitch, single-layer job. Steep and complex roofs adjust automatically.",
        placeholder: "140",
        prefix: "$",
        suffix: "/sq",
        marketRange: { low: 90, high: 185, label: "Typical range: $90 to $185/sq" },
        fieldKey: "labor",
      },
      {
        id: "shingleArch",
        type: "currency",
        question: "Supplier cost for architectural shingles per square?",
        hint: "30-year laminated — your most common Better tier product.",
        placeholder: "130",
        prefix: "$",
        suffix: "/sq",
        marketRange: { low: 95, high: 160, label: "Typical supplier cost: $95 to $160/sq" },
        fieldKey: "shingleArch",
      },
      {
        id: "shingle3Tab",
        type: "currency",
        question: "Cost for 3-tab shingles per square?",
        hint: "25-year standard grade — your Good tier.",
        placeholder: "95",
        prefix: "$",
        suffix: "/sq",
        marketRange: { low: 70, high: 115, label: "Typical: $70 to $115/sq" },
        fieldKey: "shingle3Tab",
      },
      {
        id: "shinglePremium",
        type: "currency",
        question: "Cost for premium / designer shingles per square?",
        hint: "Lifetime rated, premium profile — your Best tier.",
        placeholder: "190",
        prefix: "$",
        suffix: "/sq",
        marketRange: { low: 150, high: 230, label: "Typical: $150 to $230/sq" },
        fieldKey: "shinglePremium",
      },
      {
        id: "tearoff1",
        type: "currency",
        question: "Tear-off cost for one layer of shingles?",
        hint: "Labor and disposal for a single-layer tear-off, per square.",
        placeholder: "40",
        prefix: "$",
        suffix: "/sq",
        marketRange: { low: 25, high: 60, label: "Typical: $25 to $60/sq" },
        fieldKey: "tearoff1",
      },
      {
        id: "tearoff2",
        type: "currency",
        question: "Tear-off cost for two layers?",
        hint: "Two-layer tear-off is significantly more work and disposal weight.",
        placeholder: "70",
        prefix: "$",
        suffix: "/sq",
        marketRange: { low: 45, high: 95, label: "Typical: $45 to $95/sq" },
        fieldKey: "tearoff2",
      },
      {
        id: "icewater",
        type: "choice",
        question: "How do you install ice and water shield?",
        hint: "This affects material cost on Better and Best tiers.",
        options: [
          { value: "fulldeck", label: "Full deck",         desc: "Required in freeze-thaw climates" },
          { value: "eaves",    label: "Eaves only (6 ft)", desc: "Standard in warmer climates" },
          { value: "none",     label: "Not standard here", desc: "Tropical or warm regions" },
        ],
        fieldKey: "icewaterStyle",
      },
      {
        id: "permit",
        type: "currency",
        question: "Typical permit fee per job?",
        hint: "Flat fee per job. Check your county fee schedule.",
        placeholder: "450",
        prefix: "$",
        suffix: "flat",
        marketRange: { low: 150, high: 800, label: "Varies widely by county: $150 to $800" },
        fieldKey: "permit",
      },
      {
        id: "disposal",
        type: "currency",
        question: "Dumpster and disposal cost per job?",
        hint: "Higher in rural areas with longer haul distances.",
        placeholder: "550",
        prefix: "$",
        suffix: "flat",
        marketRange: { low: 300, high: 800, label: "Typical: $300 to $800" },
        fieldKey: "disposal",
      },
      {
        id: "marginBetter",
        type: "percent",
        question: "Target margin on your Better tier?",
        hint: "Applied to total cost — covers overhead and profit. Most contractors run 35 to 45% on their standard install.",
        placeholder: "38",
        suffix: "%",
        marketRange: { low: 30, high: 50, label: "Typical: 30 to 50%" },
        fieldKey: "marginBetter",
      },
    ],
    ghlFields: [
      "price_good","price_better","price_best","price_per_unit",
      "roof_pitch","roof_squares","roof_complexity","roof_footprint",
      "roof_material","year_built","confidence_score",
      "property_address","estimate_url","lead_source",
    ],
    defaultPricebook: {
      shingle3Tab: 95, shingleArch: 130, shinglePremium: 190,
      labor: 140, tearoff1: 40, tearoff2: 70,
      underlayment: 22, icewater: 55, misc: 18,
      permit: 450, disposal: 550,
      marginGood: 0.30, marginBetter: 0.38, marginBest: 0.48,
      icewaterStyle: "fulldeck",
    },
  },

  windows: {
    id: "windows",
    label: "Window Replacement",
    icon: "🪟",
    status: "live",
    workerEndpoint: "/analyze-windows",
    description: "AI counts windows, detects types, Good/Better/Best pricing",
    avgTicket: "$7,200",
    pricebookQuestions: [
      {
        id: "pricePerWindow",
        type: "currency",
        question: "Base price per window installed?",
        hint: "Standard double-hung, fully installed including labor. Bay/bow windows multiply from this.",
        placeholder: "350",
        prefix: "$",
        suffix: "/window",
        marketRange: { low: 250, high: 600, label: "Typical installed: $250 to $600/window" },
        fieldKey: "pricePerWindow",
      },
      {
        id: "bayBowMultiplier",
        type: "multiplier",
        question: "Bay/bow window price multiplier?",
        hint: "How many times your standard window price for a bay or bow installation.",
        placeholder: "3.5",
        suffix: "x",
        marketRange: { low: 2.5, high: 5, label: "Typical: 2.5 to 5x standard price" },
        fieldKey: "bayBowMultiplier",
      },
      {
        id: "marginBetter",
        type: "percent",
        question: "Target margin on Better tier?",
        placeholder: "40",
        suffix: "%",
        marketRange: { low: 30, high: 55, label: "Typical: 30 to 55%" },
        fieldKey: "marginBetter",
      },
    ],
    ghlFields: [
      "price_good","price_better","price_best","price_per_unit",
      "window_count","stories","year_built","install_type",
      "lead_paint_flag","property_address","estimate_url",
    ],
    defaultPricebook: {
      pricePerWindow: 350,
      bayBowMultiplier: 3.5,
      marginGood: 0.28, marginBetter: 0.40, marginBest: 0.52,
    },
  },

  garage: {
    id: "garage",
    label: "Garage Doors",
    icon: "🚗",
    status: "live",
    workerEndpoint: "/analyze-garage",
    description: "AI detects door count, type and style — instant quote",
    avgTicket: "$2,400",
    pricebookQuestions: [
      {
        id: "singleDoor",
        type: "currency",
        question: "Base price for a single garage door installed?",
        hint: "Standard steel panel, single-car door, fully installed.",
        placeholder: "950",
        prefix: "$",
        suffix: "/door",
        marketRange: { low: 700, high: 1400, label: "Typical: $700 to $1,400" },
        fieldKey: "singleDoor",
      },
      {
        id: "doubleDoor",
        type: "currency",
        question: "Price for a double (two-car) door installed?",
        placeholder: "1400",
        prefix: "$",
        suffix: "/door",
        marketRange: { low: 1000, high: 2200, label: "Typical: $1,000 to $2,200" },
        fieldKey: "doubleDoor",
      },
      {
        id: "marginBetter",
        type: "percent",
        question: "Target margin on Better tier?",
        placeholder: "35",
        suffix: "%",
        marketRange: { low: 25, high: 50, label: "Typical: 25 to 50%" },
        fieldKey: "marginBetter",
      },
    ],
    ghlFields: [
      "price_good","price_better","price_best","price_per_unit",
      "door_count","door_type","door_style","year_built",
      "property_address","estimate_url",
    ],
    defaultPricebook: {
      singleDoor: 950, doubleDoor: 1400, carriageUpgrade: 300,
      marginGood: 0.28, marginBetter: 0.35, marginBest: 0.45,
    },
  },

  hvac: {
    id: "hvac",
    label: "HVAC",
    icon: "❄️",
    status: "coming_soon",
    workerEndpoint: "/analyze-hvac",
    description: "HVAC replacement quoting — system sizing, equipment tiers",
    avgTicket: "$12,000",
    pricebookQuestions: [],
    ghlFields: [],
    defaultPricebook: {},
  },

  siding: {
    id: "siding",
    label: "Siding",
    icon: "🏗️",
    status: "coming_soon",
    workerEndpoint: "/analyze-siding",
    description: "Siding replacement — AI measures facade area, detects material",
    avgTicket: "$14,000",
    pricebookQuestions: [],
    ghlFields: [],
    defaultPricebook: {},
  },

  lawn: {
    id: "lawn",
    label: "Lawn Care",
    icon: "🌿",
    status: "live",
    workerEndpoint: "/analyze",
    description: "Lawn mowing and care — AI measures turf area, detects complexity",
    avgTicket: "$180/visit",
    pricebookQuestions: [
      {
        id: "baseRatePerSqft",
        type: "currency",
        question: "Rate per square foot of lawn?",
        placeholder: "0.012",
        prefix: "$",
        suffix: "/sqft",
        marketRange: { low: 0.008, high: 0.020, label: "Typical: $0.008 to $0.020/sqft" },
        fieldKey: "baseRatePerSqft",
      },
      {
        id: "minimumCharge",
        type: "currency",
        question: "Minimum charge per visit?",
        placeholder: "45",
        prefix: "$",
        suffix: "min",
        marketRange: { low: 35, high: 75, label: "Typical minimum: $35 to $75" },
        fieldKey: "minimumCharge",
      },
    ],
    ghlFields: ["price_good","price_better","price_best","lawn_sqft","property_address"],
    defaultPricebook: { baseRatePerSqft: 0.012, minimumCharge: 45, marginBetter: 0.35 },
  },
};

export const VERTICAL_LIST = Object.values(VERTICALS);
export const LIVE_VERTICALS = VERTICAL_LIST.filter(v => v.status === "live");

export const REGION_PRESETS = {
  southeast: {
    label: "Southeast / Florida",
    shingle3Tab: 75, shingleArch: 100, shinglePremium: 155,
    labor: 90, tearoff1: 28, tearoff2: 48,
    underlayment: 16, icewater: 35, misc: 12,
    permit: 250, disposal: 350,
    marginGood: 0.28, marginBetter: 0.37, marginBest: 0.46,
    icewaterStyle: "eaves",
  },
  midatlantic: {
    label: "Mid-Atlantic / Maryland",
    shingle3Tab: 95, shingleArch: 130, shinglePremium: 190,
    labor: 140, tearoff1: 40, tearoff2: 70,
    underlayment: 22, icewater: 55, misc: 18,
    permit: 450, disposal: 550,
    marginGood: 0.30, marginBetter: 0.38, marginBest: 0.48,
    icewaterStyle: "fulldeck",
  },
  northeast: {
    label: "Northeast / New York",
    shingle3Tab: 110, shingleArch: 155, shinglePremium: 225,
    labor: 185, tearoff1: 55, tearoff2: 90,
    underlayment: 26, icewater: 65, misc: 22,
    permit: 600, disposal: 650,
    marginGood: 0.33, marginBetter: 0.42, marginBest: 0.52,
    icewaterStyle: "fulldeck",
  },
  midwest: {
    label: "Midwest",
    shingle3Tab: 85, shingleArch: 115, shinglePremium: 170,
    labor: 120, tearoff1: 35, tearoff2: 60,
    underlayment: 19, icewater: 48, misc: 15,
    permit: 350, disposal: 450,
    marginGood: 0.30, marginBetter: 0.38, marginBest: 0.48,
    icewaterStyle: "fulldeck",
  },
};
