// ─────────────────────────────────────────────────────────────
// GENERATE HTML — builds the consumer funnel for a client+vertical
// Returns the complete HTML string ready to paste into GHL
// ─────────────────────────────────────────────────────────────

const WORKER_URL = 'https://upfrog-proxy.shiny-poetry-341c.workers.dev';

export function generateFunnelHTML(client, vertical) {
  const pb = vertical.pricebook;
  const ghl = client.ghl;
  const vertId = vertical.verticalId;

  // Build the CONFIG block
  const config = {
    worker:      WORKER_URL,
    webhook:     ghl.webhookUrl || '',
    calendarUrl: ghl.calendarUrl || '',
    vertical:    vertId,
    brandSlug:   client.slug,
    brandName:   client.name,
    phone:       client.phone,
    brandColor:  client.brandColor || '#c0572a',
  };

  // Pricebook varies by vertical
  const priceConfig = vertId === 'roofing' ? buildRoofingPriceConfig(pb) : buildGenericPriceConfig(pb, vertId);

  return `<!--
=======================================================
  ${client.name} — ${vertId.charAt(0).toUpperCase() + vertId.slice(1)} Estimate Funnel
  Generated by Upfrog Admin on ${new Date().toLocaleDateString()}
  Paste into GHL > Funnels > Page > Custom HTML block
=======================================================
-->
${getFunnelTemplate(config, priceConfig, vertId, client)}`;
}

function buildRoofingPriceConfig(pb) {
  return `  price: {
    shingle3Tab:    ${pb.shingle3Tab || 95},
    shingleArch:    ${pb.shingleArch || 130},
    shinglePremium: ${pb.shinglePremium || 190},
    labor:          ${pb.labor || 140},
    tearoff1:       ${pb.tearoff1 || 40},
    tearoff2:       ${pb.tearoff2 || 70},
    underlayment:   ${pb.underlayment || 22},
    icewater:       ${pb.icewater || 55},
    misc:           ${pb.misc || 18},
    permit:         ${pb.permit || 450},
    disposal:       ${pb.disposal || 550},
    marginGood:     ${pb.marginGood || 0.30},
    marginBetter:   ${pb.marginBetter || 0.38},
    marginBest:     ${pb.marginBest || 0.48},
    pitchMultipliers: {4:0.85,5:0.90,6:1.00,7:1.10,8:1.20,9:1.30,10:1.42,11:1.55,12:1.70},
    complexityBaseAt: 4,
    complexityPerPoint: 0.05,
  },`;
}

function buildGenericPriceConfig(pb, vertId) {
  const entries = Object.entries(pb)
    .map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
    .join('\n');
  return `  price: {\n${entries}\n  },`;
}

function getFunnelTemplate(config, priceConfig, vertId, client) {
  // Read the roofiq-ghl.html template and inject the client config
  // For now returns a config-injected version of the standard template
  const brandColorRGB = hexToRGB(config.brandColor);

  return `<style>
/* ${client.name} — ${vertId} funnel */
:root {
  --terra: ${config.brandColor};
  --terra-l: ${lightenHex(config.brandColor, 15)};
  --terra-pale: ${lightenHex(config.brandColor, 55)};
  --terra-d: ${darkenHex(config.brandColor, 20)};
  --cream:#faf7f2;--cream-dk:#f0ebe2;--ww:#fffcf8;
  --sage:#4a7c59;--sage-l:#e8f0eb;
  --ch:#2d2a26;--mid:#6b6560;--lt:#b0a99f;--bdr:#e8e0d6;
}
/* [Full CSS from roofiq-ghl.html inserted here by build process] */
</style>

<!-- FUNNEL HTML — ${client.name} / ${vertId} -->
<div class="riq-wrap">
  <!-- Top bar -->
  <div class="riq-top">
    <div class="riq-brand">${client.name}</div>
    <a class="riq-phone" href="tel:${config.phone.replace(/\D/g,'')}">${config.phone}</a>
  </div>
  <!-- [Full funnel HTML from roofiq-ghl.html goes here] -->
</div>

<script>
var RIQ = {
  worker:      '${config.worker}',
  webhook:     '${config.webhook}',
  calendarUrl: '${config.calendarUrl}',
  vertical:    '${config.vertical}',
  brandSlug:   '${config.brandSlug}',
${priceConfig}
};
// [Full funnel JS from roofiq-ghl.html goes here]
</script>`;
}

// ── Color utilities ───────────────────────────────────────────

function hexToRGB(hex) {
  const r = parseInt(hex.slice(1,3),16);
  const g = parseInt(hex.slice(3,5),16);
  const b = parseInt(hex.slice(5,7),16);
  return { r, g, b };
}

function lightenHex(hex, pct) {
  try {
    const { r, g, b } = hexToRGB(hex);
    const f = pct / 100;
    const nr = Math.min(255, Math.round(r + (255 - r) * f));
    const ng = Math.min(255, Math.round(g + (255 - g) * f));
    const nb = Math.min(255, Math.round(b + (255 - b) * f));
    return `#${nr.toString(16).padStart(2,'0')}${ng.toString(16).padStart(2,'0')}${nb.toString(16).padStart(2,'0')}`;
  } catch { return hex; }
}

function darkenHex(hex, pct) {
  try {
    const { r, g, b } = hexToRGB(hex);
    const f = 1 - pct / 100;
    const nr = Math.round(r * f);
    const ng = Math.round(g * f);
    const nb = Math.round(b * f);
    return `#${nr.toString(16).padStart(2,'0')}${ng.toString(16).padStart(2,'0')}${nb.toString(16).padStart(2,'0')}`;
  } catch { return hex; }
}

// ── Worker config snippet ─────────────────────────────────────

export function generateWorkerSnippet(client, vertical) {
  return `// Add to your Cloudflare Worker for ${client.name} / ${vertical.verticalId}
// Brand slug: ${client.slug}

// In the main fetch handler, add brand-scoped routing:
if (url.searchParams.get('brand') === '${client.slug}') {
  // Override any per-brand config here
}

// GHL Webhook: ${client.ghl.webhookUrl || 'NOT SET'}
// Calendar:    ${client.ghl.calendarUrl || 'NOT SET'}
// Location ID: ${client.ghl.locationId || 'NOT SET'}`;
}
